# Write your code here :-)
print('Hello, world!')
print('What is your name?')
myName = input()
print('It is good to meet you, ' + myName)
print('The length of your name is: {0}'.format(len(myName)))
print('What is your age?')
myAge = input()
print('You will be {0} in a year.'.format(int(myAge)+1))
